a=int(input("dati primul numar:"))
b=int(input("dati al doilea numar:"))
c=int(input("dati al treilea numar:"))
print("numarul 1:",a,b,c)
print("numarul 2:",a,c,b)
print("numarul 3:",b,a,c)
print("numarul 4:",c,a,b)
print("numarul 5:",c,b,a)